import { useQuery } from '@tanstack/react-query';
import { format } from 'date-fns';
import { motion } from 'framer-motion';
import { Flame, Repeat, CheckCircle2 } from 'lucide-react';
import api from '../../api';
import Loader from '../../components/Loader';
import { staggerContainer, staggerItem, fadeUp } from '../../lib/motion';

export default function RecurringIssues() {
  const { data: threads, isLoading } = useQuery({
    queryKey: ['recurring-issues'],
    queryFn: async () => (await api.get('/admin/complaints/recurring')).data
  });

  return (
    <motion.div initial="hidden" animate="show" variants={staggerContainer(0.06)} className="mx-auto grid max-w-3xl gap-6">
      <motion.div variants={fadeUp}>
        <h1 className="font-display text-3xl font-semibold text-ink">Recurring issues</h1>
        <p className="mt-1 text-sm text-muted">
          Threads generated by Recurrence Intelligence &mdash; issues in the same block &amp; category within 30 days.
        </p>
      </motion.div>

      {isLoading ? <Loader height="30vh" /> : threads?.length === 0 ? (
        <motion.div variants={fadeUp} className="rounded-2xl border border-dashed border-border-strong bg-surface p-12 text-center">
          <CheckCircle2 size={28} className="mx-auto mb-3 text-emerald-500" />
          <h3 className="font-display text-lg font-semibold text-ink">No recurring issues</h3>
          <p className="mt-1 text-sm text-muted">Nothing chronic is developing right now.</p>
        </motion.div>
      ) : (
        <div className="grid gap-4">
          {threads?.map(thread => (
            <motion.div
              variants={staggerItem}
              key={thread.id}
              whileHover={{ y: -2 }}
              className="rounded-2xl border border-border-c bg-surface p-6 shadow-soft transition-shadow hover:shadow-lift"
              style={{ borderLeftWidth: 4, borderLeftColor: '#ef4444' }}
            >
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-start gap-3.5">
                  <span className="mt-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-red-500/10 text-red-300">
                    <Repeat size={18} />
                  </span>
                  <div>
                    <h2 className="font-display text-xl font-semibold text-ink">
                      Block {thread.block} &mdash; {thread.category.name}
                    </h2>
                    <div className="mt-1 text-sm text-muted">
                      First reported {format(new Date(thread.firstReportedAt), 'PPP')}
                      <br />
                      Last reported {format(new Date(thread.lastReportedAt), 'PPP')}
                    </div>
                  </div>
                </div>
                <div className="shrink-0 text-right">
                  <div className="text-3xl font-bold text-red-400">{thread.recurrenceCount}</div>
                  <div className="text-xs font-semibold uppercase tracking-wide text-muted-2">Reports</div>
                  {thread.autoEscalated && (
                    <span className="mt-2 inline-flex items-center gap-1 rounded bg-red-500/10 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-red-300">
                      <Flame size={10} /> Auto-escalated
                    </span>
                  )}
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </motion.div>
  );
}
