import { useQuery } from '@tanstack/react-query';
import api from '../../utils/api';
import { format } from 'date-fns';

export default function RecurringIssues() {
  const { data: threads, isLoading } = useQuery({
    queryKey: ['recurring-issues'],
    queryFn: async () => (await api.get('/admin/complaints/recurring')).data
  });

  return (
    <div className="grid gap-6">
      <h1 className="text-2xl font-bold">Recurring Issues</h1>
      <p className="text-gray-600 -mt-4">
        Threads generated by Recurrence Intelligence (issues in same block & category within 30 days).
      </p>

      {isLoading ? <div>Loading...</div> : (
        <div className="grid gap-4">
          {threads?.map(thread => (
            <div key={thread.id} className="bg-white p-6 rounded shadow border-l-4 border-red-500">
              <div className="flex justify-between items-start mb-4">
                <div>
                  <h2 className="text-xl font-bold">Block {thread.block} - {thread.category.name}</h2>
                  <div className="text-sm text-gray-500 mt-1">
                    First reported: {format(new Date(thread.firstReportedAt), 'PPP')} <br/>
                    Last reported: {format(new Date(thread.lastReportedAt), 'PPP')}
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-3xl font-bold text-red-600">{thread.recurrenceCount}</div>
                  <div className="text-sm font-semibold text-gray-500">Reports</div>
                  {thread.autoEscalated && (
                    <span className="inline-block mt-2 px-2 py-1 bg-red-100 text-red-800 text-xs font-bold rounded">
                      AUTO ESCALATED
                    </span>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
